CREATE TABLE IF NOT EXISTS
    FOOD_ITEM
    (
        ID DECIMAL(65535,32767) AUTO_INCREMENT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255) NOT NULL,
        COST DECIMAL(65535,32767) NOT NULL,
        ICON VARCHAR(255) NOT NULL,
        PRIMARY KEY (ID)
    );
CREATE TABLE IF NOT EXISTS
    FOOD_ORDER
    (
        ID DECIMAL(65535,32767) AUTO_INCREMENT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        ADDRESS1 VARCHAR(255) NOT NULL,
        ADDRESS2 VARCHAR(255),
        CITY VARCHAR(255) NOT NULL,
        STATE VARCHAR(255) NOT NULL,
		EMAIL VARCHAR(255) NOT NULL,
        TEL DECIMAL(65535,32767) NOT NULL,
        COST DECIMAL(65535,32767) NOT NULL,
		STATUS VARCHAR(255) NOT NULL, 
		PAID BOOLEAN NOT NULL,
		PAYMENT_TYPE VARCHAR(255) NOT NULL,
        PRIMARY KEY (ID)
    );
CREATE TABLE IF NOT EXISTS
    FOOD_ORDER_ITEMS
    (
		ID DECIMAL(65535,32767) AUTO_INCREMENT NOT NULL,
		ORDER_ID DECIMAL(65535,32767) NOT NULL,
        ITEM_ID DECIMAL(65535,32767) NOT NULL,
        QUANTITY DECIMAL(65535,32767) NOT NULL,
        PRIMARY KEY (ID),
        CONSTRAINT ORDER_ITEMS_ITEM_ID_FK FOREIGN KEY (ITEM_ID) REFERENCES FOOD_ITEM (ID) ON
    DELETE
        RESTRICT,
        CONSTRAINT ORDER_ITEMS_ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES FOOD_ORDER (ID)
    ON
    DELETE
        RESTRICT
    );